blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
combine_control_expr = true
wrap_comments = true
condense_wildcard_suffixes = true
edition = "2021"
fn_params_layout = "Vertical"
fn_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = false
hex_literal_case = "Lower"
imports_layout = "Vertical"
inline_attribute_width = 50
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 32767 # ((2 ^ 16) / 2) - 1 - it looks aesthetically pleasing to have the attributes inline
use_field_init_shorthand = true